name: Suggest
description: Suggest how to improve the UPPMAX documentation
title: "Suggest: "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    label: Thanks
    value: |
      Thanks for suggesting how to make these pages better!

      What do you suggest?
- type: textarea
  attributes:
    label: Your suggestion
    value: 
